# Use Node.js image
FROM node:18

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    i2c-tools \
    python3 \
    make \
    g++ \ 
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

RUN npm install coffee-script@1.12.7 --save

# Copy package.json and install dependencies
COPY package.json /app/package.json

RUN npm install

# Copy the application code
COPY . /app

# Expose the port if necessary
EXPOSE 3003

# Run the application
CMD ["node", "app.js"]
