services:
  camera-feed-object-detection:
    build:
      context: ./camera-feed-object-detection-tensorflowjs  # Path to Dockerfile in subdirectory
    container_name: camera-detection-service
    ports:
      - "3000:3000"  # Exposing the port for this service (if needed)
    networks:
      - internal-net  # Internal network for communication
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883  # Connect to MQTT broker

  astar-pathfinder:
    build:
      context: ./astar-pathfinder-obstacle-avoidance-node  # Path to Dockerfile in subdirectory
    container_name: astar-pathfinder-service
    networks:
      - internal-net
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883  # Connect to MQTT broker

  pid-balance-control:
    build:
      context: ./PID-balance-control  # Path to Dockerfile in subdirectory
    container_name: pid-balance-control-service
    privileged: true  # Enable privileged mode for GPIO and I2C access
    devices:
      - /dev/i2c-1:/dev/i2c-1  # Map I2C device
      - /dev/gpiomem:/dev/gpiomem  # Map GPIO memory
    networks:
      - internal-net
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883  # Connect to MQTT broker
    restart: unless-stopped

  frontend-web-api:
    build:
      context: ./frontend-web-api  # Path to Dockerfile in subdirectory
    container_name: frontend-service
    ports:
      - "8080:8080"  # Expose port 8080 to make the frontend accessible externally
    networks:
      - internal-net
      - external-net  # Expose to external network
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883  # Connect to MQTT broker

  mqtt-broker:
    image: eclipse-mosquitto:latest  # Using the Eclipse Mosquitto MQTT broker
    container_name: mqtt-broker
    ports:
      - "1883:1883"  # Exposing MQTT broker port for internal services
    networks:
      - internal-net
    volumes:
      - ./mosquitto/config:/mosquitto/config  # Optional: Configuration folder
      - ./mosquitto/data:/mosquitto/data      # Optional: Data persistence
      - ./mosquitto/log:/mosquitto/log        # Optional: Log folder
    restart: unless-stopped

networks:
  internal-net:
    driver: bridge  # Internal network for communication between services
  external-net:
    driver: bridge  # External network to expose frontend
