# Use the official Node.js image
FROM node:16

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .
COPY /config.json /usr/src/app/config.json

# Expose port 3004
EXPOSE 3004

# Start the server
CMD ["node", "server.js"]
