# Use an official Node.js runtime as a parent image
FROM node:23.0.0-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install any needed dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 3008

# Command to run the application
CMD ["node", "app.js"]
