# Use Node.js base image
FROM node:18-buster

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Set the environment variable for mocking I2C device
ENV MOCK_I2C_DEVICE="/dev/i2c-mock"

# Copy application code and mock directory into the container
COPY . .

# Expose the port (if your application listens on a port)
EXPOSE 3004

# Run the application
CMD ["node", "index.js"]
